sudo: required
services:
  - docker

before_install:
  - docker build -t kayam3/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kayam3/react-test npm test  

after_success:
  - docker build -t kayam3/multi-client ./client 
  - docker build -t kayam3/multi-nginx ./nginx 
  - docker build -t kayam3/multi-server ./server
  - docker build -t kayam3/multi-worker ./worker
  # Log in to docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kayam3/multi-client 
  - docker push kayam3/multi-nginx
  - docker push kayam3/multi-server 
  - docker push kayam3/multi-worker